export const GET_ALL_REVIEWS="GET_ALL_REVIEWS";
export const SORT="SORT";
export const SORT_DECREASE="SORT_DECREASE";
export const FILTER_BY_VALUE="FILTER_BY_VALUE";
export const FILTER_BY_RANGE="FILTER_BY_RANGE";
export const RESET_RATING_FILTER="RESET_RATING_FILTER";
